language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  app: react-18-sample-1
  api_key:
    secure: jtvyam5FXvrkYMPUTUpXnXn0lNhwRneYWmmyiXqwdTKOZ5ijQHmaVzK/Qe/03C+r2b7PFrfNpCtrY9CY9I6IpCS/Wi0scLnw9kY85mSl168IjAn4Evd5xO+ICH66UnAsUEB0XalEc8qntIsH7Q506VAWmb/kOuOyk2kwC+85Y5V50hvVhzPr7PQySeAciscvNJxi2FcRzdkmxEZPbtkoWZ1RHADa35RKTzEwkShHI8iTmWMtEU0uK4YXucXy02mPYpmRk9oKQ3EG/f9OCAw2wsEJ8JK0THnZkPT22XNLtGBkuQCQUZyCY/bq0tteCH2ydVC8pHixFHN4a+A0bJV8flOWYs+Oxny5L395aSJKUcc2/XoE6qd8jKAJZOcVUqAMw7ohAx2nkr6+RrVmrCEP7XMrmLspZRbOJvNZO8t4mtzAJ8O0D4wKzUNEcsGdx9Gju9srt32ofyQLQgcu2jcm+mp9eTVe7qq32uwJRRvUrMwSQecEFInW4WcJhkOHcQH7EcAjMG/u8gaj9yLODWubl7VvVQKb0N10N30Qk64Le8sG9TLR3r7KgLFrLcCRuLYW0UgGG+1+GwJIxwlEK72hI7hLHrdKNxKznexWoTnyXbPascVANcoH1l+63WMBEo5uQx0HDF1Svcax5F/oygsXMHKbVET7rBTn3xXkzNKkt+s=
  skip_cleanup: true
