language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  app: react-18-sample-1
  api_key:
    secure: QKlq6C8ZlOdj3qWro4uuN9deVbmwVXjcmgqRPO9s/QZxTPN5w8vdR+i07BmBfbyOblEOpddit5JxOrr7/L7VuVja7ph9SBIdee4SO6IPwPHAQfNCxz6eqJO7vQMbK7SfDYAQIhS0c4QRx36udEf91Mcl+wYERfbOnmBOvJfbajeDwWmDzkSd637Zt7mQIYlXYOXYqA9ytot9de3Jpg9TSwuJGUEUIsydVI9rtqpssloh6wor0mIBqFq5Dd888jFLruhWNv4+OUzhy7h94NOEyHGx2niiaDFzrbtx1+1HKqFvMhChZADdYyPAlzVyKT1Cgy2SLvnV8YO5diQJLRol66t8Gn3tSa46RHKDkZq2h3BbMusE27Vvvfs8hFmQ9tUB11dDhNgay1pEWjukpBEN8kgr7zOZOQYWh7Q8BgRBIFT48NqNPNZoWzz6sOhBqdRFzJ623yfeEWVlC3aBTo+kbiLXEdUFXFquoN7+6gOB6jU/V8gB3WBmPawTpLYdYdZQSt+Sd42RfBdfrWKEjuJenBytDGQKlzzt449iUGmKKBKHup/mykFhnpeRaUyLjw+4/HmHHaaWR/ZioTrUC8D2vOBS92Gfsa4GfA1fHNvKQpA4BEpi6HjZfvJyey4K/6+JAxWhfuZCZT6dmpIHRrCIZGK+M1cHHVJ6SAo0pjeUlaI=
  skip_cleanup: true
