language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  app: react-18-sample-1
  api_key:
    secure: 1W7avMZSrPq+xykWal3x2vwsaZDQxBFuQhFUJFr09LzLjZfXLclxBHDD8NrBAJ2VnJeuirk2/HLt9RQut7s/AzGFznh2vmLw3IJIpkoSJe1jyId7KjWQFQMwHvZBs83Z5o49z3cACccgo5adbKawzyjOLy3vJJaI+CPK7fjg5bLTQsfjkJhsCNFtWsU2i9pGLkwQpEX8heQlSEXdYTR1stbWR0/ygVljf/1aiS5/gMXgRQ6Et563lnkcU3AbClLl0WKQ0nEMblM+nlPmMf+r8GBHe/08k+gt1fz1fphc743CKiVepy792zCyovdKeWdE+Gxnx+fDX969yI2+6cmZMm0/V2qfNzOKm2C/6c8JcHwskqwinYabwYHaf8lQs/7cCvUWaHfnnQDnJh6ZYWWMuhp8u+R0iDhwetF/S512kM1f/DGcUyvQlDxHNhmfdz/Ua19qxdYFvwLgMI4zsydITffZv9olyDGqM0WsOCZkpOm/EV9vPnE/vyB/CDh2voFX9oiaRBhLZRVgp0ND+spSsK/jjjIWyfYYJ3WiRz6W/lDuTt4MwAmSlPSmhYdoq69PMvVh6wbkOWIcpSQj4ccRO2ZpfXV6kugVMJzwN7wP3WZVgXo1XyX7mfLNxIh/9gdL/wmo6CL8KMffLP4EbzOhEyw9fJjBrs6h9eXiNdw/vvo=
  skip_cleanup: true
