language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  app: react-18-sample-1
  api_key:
    secure: 4dfa3999-549f-48d8-9027-d8ceba4a38a2
  skip_cleanup: true
