language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  app: react-18-sample-1
  api_key:
    secure: Gm9UM5oC9neBhUmMH3sysWB/DR8UXKWswEJEEACnCVHk1lKj4Yp4p6heP87mZen8npSAwnkv2sYsG6iQE25qdYL8bFqnIeW9VFwSy+FCuZnUYVo1Z9+IbidG1g2+zY9mGS13jYOztNpPjGy8L9jDEsxB4Qz1m5TrcQBOeZGCAuC6nDlGnKxCdoMwrIHBF+y/VNZOZos/YmtS/ySZWnrFJyjawFvzOM0DicDFQYl7P8jjwYs3jFzaHEC6lgvbyF2qGXzMphk4rqz1VlfywpGelphvnbcq1H3ZGOay4oZNBVai+6IVeNHW9rUpWFu7hrs/m95Wywd7Al566/FU6BSHuVbaMXx9+HahSYDiUppIfM6gasYzpg/sNszoepwvmkT9OQ9TxpDW+9pMrnxwTWfmybISkxduAUvOQQ2L/aQ2MidZ7E7b7XK2YZcMem5n0HXMxBH4sjRabm5MxVp4cJuf6ecCcfZS8mHEsBTJRful+Jacu/L92eq+JMePBD8W5j9U/SkU5QqJc8iUi5EGRIZN+mVhOtSnBCUN0iDkkfaCWS7lCuph705TsTmLa7yQmYJReGxIw51CZc03vlz8SVK9Puc6H486BwpxvQdqSsOxGPRVYxYIt9JjLM1FzTPYzIcjjITAKTnonOP7jZYSE3OyiKa7A9YKnrpZ6OkNiWjdvZ0=
  skip_cleanup: true
